### ISSUE TITLE
Uninitialized constant HTML

### ISSUE THREAD

**Issue by mietek** [gjtorikian/html-proofer#157]
This happens both when installing from source and from RubyGems:
```
$ htmlproof
/usr/local/gems/html-proofer-2.0.0/lib/html/proofer/check_runner.rb:3:in `<top (required)>': uninitialized constant HTML (NameError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /usr/local/gems/html-proofer-2.0.0/lib/html/proofer.rb:4:in `block in require_all'
	from /usr/local/gems/html-proofer-2.0.0/lib/html/proofer.rb:3:in `each'
	from /usr/local/gems/html-proofer-2.0.0/lib/html/proofer.rb:3:in `require_all'
	from /usr/local/gems/html-proofer-2.0.0/lib/html/proofer.rb:8:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/gems/html-proofer-2.0.0/bin/htmlproof:6:in `<top (required)>'
	from /usr/local/bin/htmlproof:23:in `load'
	from /usr/local/bin/htmlproof:23:in `<main>'
```

**Comment by mietek** [comment]
Thanks.
