### ISSUE TITLE
ArgumentError: wrong number of arguments 

### ISSUE THREAD

**Issue by holic** [gjtorikian/html-proofer#162]
Currently having trouble with the latest build (2.0.2):

https://travis-ci.org/iwantmyname/blog/builds/48960602#L2761
```
rake aborted!
ArgumentError: wrong number of arguments (2 for 0)
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer/url_validator.rb:114:in `handle_timeout'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer/url_validator.rb:84:in `response_handler'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer/url_validator.rb:68:in `block in queue_request'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:129:in `call'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:129:in `block in execute_callbacks'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `map'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `execute_callbacks'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/operations.rb:35:in `finish'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/easy_factory.rb:105:in `block in set_callback'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `call'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `each'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `complete'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:148:in `check'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:161:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:43:in `perform'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/hydra/runnable.rb:15:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/hydra/memoizable.rb:51:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer/url_validator.rb:48:in `external_link_checker'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer/url_validator.rb:22:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer.rb:131:in `validate_urls'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer.rb:107:in `check_directory_of_files'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.2/lib/html/proofer.rb:75:in `run'
/home/travis/build/iwantmyname/blog/Rakefile:18:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by parkr** [comment]
Try #163 – should fix it for you.

**Comment by holic** [comment]
Thanks @parkr and @gjtorikian. However, I'm now seeing:

```
NameError: undefined local variable or method `href' for #<HTML::Proofer::UrlValidator:0x00000002482248>
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer/url_validator.rb:116:in `handle_timeout'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer/url_validator.rb:84:in `response_handler'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer/url_validator.rb:68:in `block in queue_request'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:129:in `call'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:129:in `block in execute_callbacks'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `map'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `execute_callbacks'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/request/operations.rb:35:in `finish'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/easy_factory.rb:105:in `block in set_callback'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `call'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `each'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `complete'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:148:in `check'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:161:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/ethon-0.7.2/lib/ethon/multi/operations.rb:43:in `perform'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/hydra/runnable.rb:15:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/typhoeus-0.6.9/lib/typhoeus/hydra/memoizable.rb:51:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer/url_validator.rb:48:in `external_link_checker'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer/url_validator.rb:22:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer.rb:131:in `validate_urls'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer.rb:107:in `check_directory_of_files'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.3/lib/html/proofer.rb:75:in `run'
/home/travis/build/iwantmyname/blog/Rakefile:18:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by gjtorikian** [comment]
@holic 2.0.4 should now address this.

**Comment by holic** [comment]
Thanks @gjtorikian
