### ISSUE TITLE
External link failed: response code 0 means something's wrong

### ISSUE THREAD

**Issue by zachwhaley** [gjtorikian/html-proofer#321]
When I run html-proofer locally, I get failures from the external link checks.  The failures are always the same `External link failed: response code 0 means something's wrong` but not on the same links; sometimes 13 links sometimes 23 links fail.

What is interesting is that I don't see this behavior on Travis CI.

```
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./_site"] on *.html... 


Checking 32 external links...
Ran on 166 files!


- ./_site/2014/11/22/pound-for-pound/index.html
  *  External link http://www.tomlinsons.com/ failed: response code 0 means something's wrong
- ./_site/2015/01/26/february-news-2015/index.html
  *  External link http://www.zoomroomonline.com/austin-dog-training.html failed: response code 0 means something's wrong
- ./_site/2015/03/29/april-news/index.html
  *  External link http://austinheartvet.com/ failed: response code 0 means something's wrong
- ./_site/2015/05/04/may/index.html
  *  External link http://texasfarmersmarket.org/mueller/ failed: response code 0 means something's wrong
  *  External link http://us6.campaign-archive2.com/?u=ce82f17bc088ab9ad887edb8d&id=b31d7d780c&e=43054ebcf2 failed: response code 0 means something's wrong
- ./_site/2015/06/03/june/index.html
  *  External link http://eepurl.com/boYVTX failed: response code 0 means something's wrong
  *  External link http://www.handmade4hounds.etsy.com/ failed: response code 0 means something's wrong
- ./_site/2015/10/12/october-news/index.html
  *  External link https://www.facebook.com/events/1486089575035397/ failed: response code 0 means something's wrong
- ./_site/2015/11/05/november/index.html
  *  External link https://www.etsy.com/shop/dogsbythebay failed: response code 0 means something's wrong
- ./_site/about/index.html
  *  External link http://gpacentraltexas.us6.list-manage.com/subscribe?u=ce82f17bc088ab9ad887edb8d&id=5f26041b9d failed: response code 0 means something's wrong
  *  External link http://instagram.com/greyhoundscentraltexas?ref=badge failed: response code 0 means something's wrong
  *  External link http://www.randalls.com/IFL/Grocery/Good-Neighbor failed: response code 0 means something's wrong
  *  External link http://www.wooftrax.com/ failed: response code 0 means something's wrong
  *  External link https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js failed: response code 0 means something's wrong
  *  External link https://apis.google.com/js/platform.js failed: response code 0 means something's wrong
  *  External link https://smile.amazon.com/ch/74-2762533 failed: response code 0 means something's wrong
  *  External link https://twitter.com/GPA_CenTex failed: response code 0 means something's wrong
  *  External link https://www.barkbox.com/ failed: response code 0 means something's wrong
- ./_site/greyhounds/alyann/index.html
  *  External link https://twitter.com/share failed: response code 0 means something's wrong
rake aborted!
HTML-Proofer found 19 failures!
/home/zwhaley/.gem/ruby/gems/html-proofer-3.0.4/lib/html-proofer/runner.rb:161:in `print_failed_tests'
/home/zwhaley/.gem/ruby/gems/html-proofer-3.0.4/lib/html-proofer/runner.rb:43:in `run'
/home/zwhaley/Code/gpa-centex.github.io/Rakefile:7:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by gjtorikian** [comment]
Changes pending in https://github.com/gjtorikian/html-proofer/pull/322 should help explain this.
