### ISSUE TITLE
Ignore "no error"

### ISSUE THREAD

**Issue by GarthDB** [gjtorikian/html-proofer#336]
I get inconsistent results when I run html-proofer on travis. Whenever it does return an inconsistent error it has a different code (sometimes 403, 0, etc), but always with the result "no error". It would be nice to ignore it by message since other errors with those codes could be useful.

**Comment by gjtorikian** [comment]
Could you show me an example of the Travis CI output?

**Comment by GarthDB** [comment]
Here's [one](https://travis-ci.org/phonegap/blog/builds/139537907):

```
Running ["HtmlCheck", "ImageCheck", "LinkCheck", "ScriptCheck"] on ["./_site-test"] on *.html... 
Found 0 links in the cache...
Adding 1304 links to the cache...
Removing 0 links from the cache...
Checking 1304 external links...
Ran on 390 files!
- ./_site-test/blog/2016/06/15/tapbookauthor-guest-post/index.html
  *  External link https://www.linkedin.com/in/sondresb failed: 999 No error
rake aborted!
HTML-Proofer found 1 failure!
/home/travis/.rvm/gems/ruby-2.2.3/gems/html-proofer-3.0.6/lib/html-proofer/runner.rb:161:in `print_failed_tests'
/home/travis/.rvm/gems/ruby-2.2.3/gems/html-proofer-3.0.6/lib/html-proofer/runner.rb:43:in `run'
/home/travis/build/phonegap/blog/Rakefile:290:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.2.3/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
The command "bundle exec rake test" exited with 1.
Done. Your build exited with 1.
```

**Comment by aviskase** [comment]
Also have similar link failure:

```
$ htmlproofer --check-html --assume-extension --check-favicon ./_site
Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck", "FaviconCheck"] on ["./_site"] on *.html... 
Checking 123 external links...
Ran on 25 files!
- ./_site/2016/05/en-api-and-webservices-list.html
  *  External link http://readwrite.com/2013/09/19/api-defined/ failed: 405 No error
htmlproofer 3.0.6 | Error:  HTML-Proofer found 1 failure!
```

**Comment by GarthDB** [comment]
looks like slideshare is now returning a `no error`.

```sh
- ./_site-test/blog/2015/06/10/phonegap-day-eu-2015-phonegap-2014-review/index.html
  *  External link http://www.slideshare.net/mwbrooks/phonegap-daymwbrooks failed: 999 No error
```

**Comment by markphelps** [comment]
FWIW I also get a `999 no error` on my LinkedIn link:

```
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["./_site"] on *.html...

Checking 176 external links...
Ran on 41 files!

...
- ./_site/publications.html
  *  External link https://www.linkedin.com/in/markphelps1 failed: 999 No error
rake aborted!
HTML-Proofer found 2 failures!
/Users/mark/.gem/ruby/2.2.3/gems/html-proofer-3.0.6/lib/html-proofer/runner.rb:161:in `print_failed_tests'
/Users/mark/.gem/ruby/2.2.3/gems/html-proofer-3.0.6/lib/html-proofer/runner.rb:43:in `run'
/Users/mark/Projects/markphelps.github.io/Rakefile:157:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by gjtorikian** [comment]
There is now an `http_status_ignore` configuration option which can be used to ignore status codes like `0`, `999`, etc. However, many times these problems are because the SSL certificate on the server is incorrect, or, in the case of LinkedIn, the user agent needs to change (they have banned html-proofer).
