### ISSUE TITLE
Redundant mandatory argument for "--as-links" option

### ISSUE THREAD

**Issue by geraldnguyen** [gjtorikian/html-proofer#504]
Hello.

The argument does not seem to do anything and the links to be checked are already available from the PATH argument

Examples:
```
/usr/local/lib/ruby/gems/2.6.0/bin/htmlproofer www.google.com,www.facebook.com --as-links 
Traceback (most recent call last):
	4: from /usr/local/lib/ruby/gems/2.6.0/bin/htmlproofer:23:in `<main>'
	3: from /usr/local/lib/ruby/gems/2.6.0/bin/htmlproofer:23:in `load'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/html-proofer-3.10.0/bin/htmlproofer:9:in `<top (required)>'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
/usr/local/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:31:in `go': missing argument: --as-links (OptionParser::MissingArgument)
```

```
/usr/local/lib/ruby/gems/2.6.0/bin/htmlproofer www.google.com,www.facebook.com --as-links whatever
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["www.google.com", "www.facebook.com"] on *.html... 


Checking 2 external links...
HTML-Proofer finished successfully.
```

Is the `-t` option mistaken for `--as-links`' argument?
```
/usr/local/lib/ruby/gems/2.6.0/bin/htmlproofer www.google.com,www.facebook.com --as-links -t
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["www.google.com", "www.facebook.com"] on *.html... 


Checking 2 external links...
HTML-Proofer finished successfully.
```

Please let me know if you need additional info.

Regards,
Gerald

**Comment by gjtorikian** [comment]
Thanks for the report! There was a slight logic bug that needed correcting.
