### ISSUE TITLE
HTML Proofer report is not displayed on Ruby 2.7

### ISSUE THREAD

**Issue by ferrarimarco** [gjtorikian/html-proofer#549]
Hi! While using your gem (version `3.15.0`) with ruby `2.7.0`, I noticed that it doesn't report the details of offending files, but just the total of the issues and a RunTime exception.

Here's an example:

```
bundle exec htmlproofer ./dist/index.html --assume-extension --check_favicon --check_html --check_img_http --check_sri --log_level debug
htmlproofer 3.14.1 | Error:  HTML-Proofer found 8 failures!
Traceback (most recent call last):
	25: from /Users/ferrarim/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
	24: from /Users/ferrarim/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
	23: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.2/libexec/bundle:34:in `<top (required)>'
	22: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	21: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.2/libexec/bundle:46:in `block in <top (required)>'
	20: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
	19: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	18: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
	17: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	16: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	14: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
	13: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
	12: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
	11: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
	10: from /Users/ferrarim/.rbenv/versions/2.7.0/bin/htmlproofer:23:in `<top (required)>'
	 9: from /Users/ferrarim/.rbenv/versions/2.7.0/bin/htmlproofer:23:in `load'
	 8: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/html-proofer-3.14.1/bin/htmlproofer:11:in `<top (required)>'
	 7: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	 6: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	 5: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	 4: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	 3: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	 2: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/html-proofer-3.14.1/bin/htmlproofer:105:in `block (2 levels) in <top (required)>'
	 1: from /Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/html-proofer-3.14.1/lib/html-proofer/runner.rb:50:in `run'
/Users/ferrarim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/html-proofer-3.14.1/lib/html-proofer/runner.rb:172:in `print_failed_tests': \e[31mHTML-Proofer found 8 failures!\e[0m (RuntimeError)
```

While on Ruby `2.6`:

```
bundle exec htmlproofer ./dist/index.html --assume-extension --check_favicon --check_html --check_img_http --check_sri --log_level debug
Running ["ImageCheck", "ScriptCheck", "HtmlCheck", "FaviconCheck", "LinkCheck"] on ./dist/index.html on *.html...


Checking imagecheck on ./dist/index.html ...
Checking scriptcheck on ./dist/index.html ...
Checking htmlcheck on ./dist/index.html ...
Checking faviconcheck on ./dist/index.html ...
Checking linkcheck on ./dist/index.html ...
Checking 10 external links...
ETHON: started MULTI
Received a 200 for https://fonts.googleapis.com/css?family=Roboto+Slab%7CRoboto  in ./dist/index.html
Received a 999 for https://www.linkedin.com/in/ferrarimark  in ./dist/index.html
Received a 999 for https://www.linkedin.com/in/ferrarimark  in ./dist/index.html
Received a 200 for https://ferrarimarco.info/  in ./dist/index.html
Received a 200 for https://ferrarimarco.info/feed.xml  in ./dist/index.html
Received a 200 for https://stackoverflow.com/users/653462  in ./dist/index.html
Received a 200 for https://twitter.com/ferrarimarco  in ./dist/index.html
Received a 200 for https://github.com/ferrarimarco  in ./dist/index.html
Received a 200 for https://www.facebook.com/ferrari.marco  in ./dist/index.html
Received a 200 for https://bit.ly/ferrari-marco-cv-ita  in ./dist/index.html
Received a 200 for https://bit.ly/ferrari-marco-cv-eng  in ./dist/index.html
ETHON: performed MULTI
Ran on 1 file!


- ./dist/index.html
  *  External link https://www.linkedin.com/in/ferrarimark failed: 999 No error
  *  SRI and CORS not provided in:  (line 1)
     <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Roboto" rel="stylesheet" type="text/css">
  *  image /assets/images/contacts/email.png does not have an alt attribute (line 3)
  *  image /assets/images/contacts/facebook.png does not have an alt attribute (line 3)
  *  image /assets/images/contacts/github.png does not have an alt attribute (line 3)
  *  image /assets/images/contacts/linkedin.png does not have an alt attribute (line 3)
  *  image /assets/images/contacts/stackoverflow.png does not have an alt attribute (line 3)
  *  image /assets/images/contacts/twitter.png does not have an alt attribute (line 3)
htmlproofer 3.15.0 | Error:  HTML-Proofer found 8 failures!
```

**Comment by gjtorikian** [comment]
Thanks for the report--a very weird issue! I've fixed the bug and update CI to ensure that 2.7 is tested. A patch release supporting this is also out now.

PS: if it so happens that Google is relying on this project, please consider sponsoring. Thanks. ✌️

**Comment by ferrarimarco** [comment]
Lol, it's for my personal website :)

**Comment by ferrarimarco** [comment]
Great project btw!
