### ISSUE TITLE
RuntimeError's are printed for 404 failures

### ISSUE THREAD

**Issue by nickoe** [gjtorikian/html-proofer#575]
I have been using html-proofer for some time now, and recently at least, I have been a bit confused when it detects a 404 because html-proofer also prints a RuntimeError.

I am using 3.15.3 or 3.13.0 on Ruby 2.7.1.

Run as:
```
htmlproofer ./public --external_only --only_4xx --url-ignore "/www.digikey.com/"
```
Output:
```
Running ["ScriptCheck", "ImageCheck", "LinkCheck"] on ["./public"] on *.html... 
Checking 462 external links...
Ran on 345 files!
- ./public/blog/2019/02/First-Annual-KiCad-Conference-Announcement/index.html
  *  External link https://kicad-kicon.com/sponsors/ failed: 404 No error
htmlproofer 3.15.3 | Error:  HTML-Proofer found 1 failure!
/usr/local/bundle/gems/html-proofer-3.15.3/lib/html-proofer/runner.rb:174:in `print_failed_tests': HTML-Proofer found 1 failure! (RuntimeError)
	from /usr/local/bundle/gems/html-proofer-3.15.3/lib/html-proofer/runner.rb:50:in `run'
	from /usr/local/bundle/gems/html-proofer-3.15.3/bin/htmlproofer:109:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/local/bundle/gems/html-proofer-3.15.3/bin/htmlproofer:11:in `<top (required)>'
	from /usr/local/bundle/bin/htmlproofer:23:in `load'
	from /usr/local/bundle/bin/htmlproofer:23:in `<main>'
```
This makes me personally unsure if there is only one error on the website, as I would expect a RuntimeError to abort even before it has finished checking everything.

**Comment by riccardoporreca** [comment]
Reported also in #608 and fixed since long by #609
