### ISSUE TITLE
Broken links to internal hash reported for wrong file (3.17.0+)

### ISSUE THREAD

**Issue by marmarek** [gjtorikian/html-proofer#602]
Staring with 3.17.0 (applicable to 3.17.2 too), broken links are reported in a wrong file.

Broken output:
```
$ htmlproofer ./_site --disable-external --checks-to-ignore ImageCheck --file-ignore ./_site/video-tours/index.html --only_4xx --url-ignore /qubes-issues/  
Running ["ScriptCheck", "LinkCheck"] on ["./_site"] on *.html... 


Ran on 989 files!


- ./_site/downloads/index.html
  *  linking to internal hash #generating-and-submitting-new-report that does not exist (line 0)
     <a href="/doc/hcl/#generating-and-submitting-new-report">generating and submitting a Hardware
Compatibility List (HCL) report</a>
htmlproofer 3.17.2 | Error:  HTML-Proofer found 1 failure!
Traceback (most recent call last):
	10: from /home/user/bin/htmlproofer:23:in `<main>'
	 9: from /home/user/bin/htmlproofer:23:in `load'
	 8: from /home/user/.gem/ruby/gems/html-proofer-3.17.2/bin/htmlproofer:11:in `<top (required)>'
	 7: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	 6: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	 5: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	 4: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	 3: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	 2: from /home/user/.gem/ruby/gems/html-proofer-3.17.2/bin/htmlproofer:109:in `block (2 levels) in <top (required)>'
	 1: from /home/user/.gem/ruby/gems/html-proofer-3.17.2/lib/html-proofer/runner.rb:56:in `run'
/home/user/.gem/ruby/gems/html-proofer-3.17.2/lib/html-proofer/runner.rb:214:in `print_failed_tests': \e[31mHTML-Proofer found 1 failure!\e[0m (RuntimeError)
```

Correct output (3.16.0):
```
$ htmlproofer ./_site --disable-external --checks-to-ignore ImageCheck --file-ignore ./_site/video-tours/index.html --only_4xx --url-ignore /qubes-issues/  
Running ["LinkCheck", "ScriptCheck"] on ["./_site"] on *.html... 


Ran on 989 files!


- ./_site/support/index.html
  *  linking to internal hash #generating-and-submitting-new-report that does not exist (line 0)
     <a href="/doc/hcl/#generating-and-submitting-new-report">generating and submitting a Hardware
Compatibility List (HCL) report</a>
htmlproofer 3.16.0 | Error:  HTML-Proofer found 1 failure!
Traceback (most recent call last):
	10: from /home/user/bin/htmlproofer:23:in `<main>'
	 9: from /home/user/bin/htmlproofer:23:in `load'
	 8: from /home/user/.gem/ruby/gems/html-proofer-3.16.0/bin/htmlproofer:11:in `<top (required)>'
	 7: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	 6: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	 5: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	 4: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	 3: from /home/user/.gem/ruby/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	 2: from /home/user/.gem/ruby/gems/html-proofer-3.16.0/bin/htmlproofer:109:in `block (2 levels) in <top (required)>'
	 1: from /home/user/.gem/ruby/gems/html-proofer-3.16.0/lib/html-proofer/runner.rb:51:in `run'
/home/user/.gem/ruby/gems/html-proofer-3.16.0/lib/html-proofer/runner.rb:176:in `print_failed_tests': \e[31mHTML-Proofer found 1 failure!\e[0m (RuntimeError)
```

Manual search for the url fragment (the broken one is missing 's' at the end):
```
$ grep -rn generating-and-submitting-new-report
_site/hcl/index.html:157:        <a href="/doc/hcl/#generating-and-submitting-new-reports" class="btn btn-default btn-block" href=""><i class="fa fa-plus"></i> Add Your Device</a>
_site/hcl/index.html:162:        <li><a href="/doc/hcl/#generating-and-submitting-new-reports">How do I Submit a Report?</a></li>
_site/doc/hcl/index.html:249:<h2 id="generating-and-submitting-new-reports">Generating and Submitting New Reports</h2>
_site/doc/system-requirements/index.html:295:(See <a href="/doc/hcl/#generating-and-submitting-new-reports">hcl-report</a> for advice on hardware compatibility testing.)
_site/doc/reporting-bugs/index.html:289:A great way to do this is by <a href="/doc/hcl/#generating-and-submitting-new-reports">generating and submitting a Hardware Compatibility List (HCL) report</a>, then linking to it in your issue.
_site/doc/installation-guide/index.html:579:<p>Consider giving back to the Qubes community and helping other users by <a href="/doc/hcl/#generating-and-submitting-new-reports">generating and submitting a Hardware Compatibility List (HCL) report</a>.</p>
_site/doc/install-nvidia-driver/index.html:246:<a href="/doc/hcl/#generating-and-submitting-new-reports">Hardware Compatibility List (HCL)</a>
_site/news/2016/09/02/4-0-minimum-requirements-3-2-extended-support/index.html:268:consider <a href="https://www.qubes-os.org/doc/hcl/#generating-and-submitting-new-reports">submitting an HCL report</a> of your own.</p>
_site/news/2016/09/02/4-0-minimum-requirements-3-2-extended-support/index.html:277:<p>In addition, the <code class="language-plaintext highlighter-rouge">qubes-hcl-report</code> tool, which is used for  <a href="https://www.qubes-os.org/doc/hcl/#generating-and-submitting-new-reports">submitting an HCL
_site/support/index.html:416:provide your hardware details is by <a href="/doc/hcl/#generating-and-submitting-new-report">generating and submitting a Hardware
```
As you can see, the broken link is only in the last result (`_site/support/index.html`), and it is not present `./_site/downloads/index.html` at all (neither good or broken one).

I can share built site archive if necessary (it's 62MB archive so I'm not attaching it here).

PS Is the "RuntimeError" exception expected? Shouldn't that be just the last line printed without the whole traceback?

**Comment by gjtorikian** [comment]
Sorry about that, but thank you for the detailed report. A new patch release has fixed this.
