### ISSUE TITLE
NoMethodError: undefined method `link'

### ISSUE THREAD

**Issue by stevecheckoway** [gjtorikian/html-proofer#604]
html-proofer crashes when run with items in the cache that have expired.

```
Running ["HtmlCheck", "ScriptCheck", "LinkCheck", "ImageCheck"] on ["_staging"] on *.html...


Adding 2 links to the cache...
Removing 2 links from the cache...
Found 579 internal links in the cache...
rake aborted!
NoMethodError: undefined method `link' for "_staging/index.html":String
Did you mean?  lines
/Users/steve/research/cswww/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.17.3/lib/html-proofer/runner.rb:150:in `block in validate_internal_urls'
/Users/steve/research/cswww/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.17.3/lib/html-proofer/runner.rb:149:in `each_pair'
/Users/steve/research/cswww/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.17.3/lib/html-proofer/runner.rb:149:in `validate_internal_urls'
/Users/steve/research/cswww/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.17.3/lib/html-proofer/runner.rb:89:in `check_files'
/Users/steve/research/cswww/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.17.3/lib/html-proofer/runner.rb:48:in `run'
/Users/steve/research/cswww/Rakefile:99:in `block in <top (required)>'
/Users/steve/research/cswww/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

I tried to track this down the other day but couldn't reproduce it because deleting the cache fixes the issue.

Indeed, after deleting the cache directory, running it produces
```
Running ["LinkCheck", "ImageCheck", "HtmlCheck", "ScriptCheck"] on ["_staging"] on *.html...


Adding 579 links to the cache...
Removing 0 links from the cache...
Found 579 internal links in the cache...
Ran on 203 files!


HTML-Proofer finished successfully.
```
Notice that it says it found links in the cache.

If I run it immediately afterward, I get a surprising result.
```
Running ["LinkCheck", "ImageCheck", "HtmlCheck", "ScriptCheck"] on ["_staging"] on *.html...


Adding 0 links to the cache...
Removing 0 links from the cache...
Found 0 internal links in the cache...
Ran on 203 files!


HTML-Proofer finished successfully.
```

I believe this regression was introduced in 3.17.1 or 3.17.2 but I haven't had a chance to track it down yet.

**Comment by gjtorikian** [comment]
Sorry about that. New patch release should have it fixed.
