### ISSUE TITLE
Ugly runtime error when broken links exist

### ISSUE THREAD

**Issue by emmasax4** [gjtorikian/html-proofer#608]
Whenever HTML Proofer finds broken links, it throws an ugly Runtime Error:

```
htmlproofer 3.17.4 | Error:  HTML-Proofer found 62 failures!
Traceback (most recent call last):
        25: from /Users/emmasax/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
        24: from /Users/emmasax/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
        23: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/exe/bundle:37:in `<top (required)>'
        22: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        21: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/exe/bundle:49:in `block in <top (required)>'
        20: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
        19: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        18: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
        17: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        16: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        15: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        14: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:497:in `exec'
        13: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:28:in `run'
        12: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `kernel_load'
        11: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `load'
        10: from /Users/emmasax/.rbenv/versions/2.7.2/bin/htmlproofer:23:in `<top (required)>'
         9: from /Users/emmasax/.rbenv/versions/2.7.2/bin/htmlproofer:23:in `load'
         8: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.17.4/bin/htmlproofer:11:in `<top (required)>'
         7: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
         6: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
         5: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
         4: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
         3: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
         2: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.17.4/bin/htmlproofer:109:in `block (2 levels) in <top (required)>'
         1: from /Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.17.4/lib/html-proofer/runner.rb:56:in `run'
/Users/emmasax/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.17.4/lib/html-proofer/runner.rb:217:in `print_failed_tests': \e[31mHTML-Proofer found 62 failures!\e[0m (RuntimeError)
```

I'm using ruby 2.7.2, with HTML Proofer 3.17.4.

Preferably, if HTML proofer finds broken links, just politely tell me... there's no need to go crazy. AKA the response should just return `true` or `exit 0` at the end.

Any suggestions on what I can do to make this failure quieter?

**Comment by gjtorikian** [comment]
Could you share the site/HTML that caused this stack trace? The normal failure state isn’t a dump of garbage like this. Something else is afoot.

**Comment by emmasax4** [comment]
I call [this file](https://github.com/emmasax4/emmasax4.com/blob/d7b497f3df78a4ad82dbdf4ae66e06ae6b02478c/.github/scripts/html_proofer.sh) from within a GitHub Actions run. I run it on my entire site though, so linking to the HTML is difficult, but [here is the branch](https://github.com/emmasax4/emmasax4.com/tree/gh-pages) where all of my HTML lives.

I can also just run 
```
bundle exec htmlproofer _site
```
locally on my machine and it blows up with the same errors.

**Comment by emmasax4** [comment]
Excellent! I believe that pull request and update fixed the issue (see updated build [here](https://github.com/emmasax4/emmasax4.com/runs/1539194828)). Thanks for your speedy response!
