### ISSUE TITLE
NoMethodError thrown with certain malformed URLs

### ISSUE THREAD

**Issue by ExMember** [gjtorikian/html-proofer#615]
If the URL is malformed in a particular way, for example, `https:\\www.youtube.com\watch?v=QafV7WHdLHE`, external link checking will crash with a NoMethod error.

I believe the problem is here: https://github.com/gjtorikian/html-proofer/blob/main/lib/html-proofer/url_validator.rb#L74

uri.host is returning nil, which then cannot be added to uri.path.

Here is a stacktrace:

```
NoMethodError: undefined method `+' for nil:NilClass
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/url_validator.rb:74:in `extract_domain_path'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/url_validator.rb:61:in `new_url_query_values?'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/url_validator.rb:53:in `block in remove_query_values'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/url_validator.rb:44:in `each_key'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/url_validator.rb:44:in `remove_query_values'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/url_validator.rb:26:in `run'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/runner.rb:141:in `validate_external_urls'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/runner.rb:86:in `check_files'
/Users/damienburke/.rvm/gems/ruby-2.5.3/gems/html-proofer-3.18.3/lib/html-proofer/runner.rb:48:in `run'
```

**Comment by gjtorikian** [comment]
Good find!
