### ISSUE TITLE
Fatal error in 3.19.1(sh: gcc: not found)

### ISSUE THREAD

**Issue by Baltazardoung** [gjtorikian/html-proofer#638]
In a continuous integration job I use [html-proofer with docker](https://hub.docker.com/r/klakegg/html-proofer). Since `v3.19.1`  I have this error : 

```shell
docker exec html-proofer sh -c "htmlproofer site --log-level debug --empty-alt-ignore --url-ignore \"/fonts.gstatic.com/\""
/usr/local/bundle/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:131:in `block in calculate': Compilation error generating constants : (RuntimeError)
        sh: gcc: not found
        from /usr/local/lib/ruby/2.7.0/tempfile.rb:291:in `open'
        from /usr/local/bundle/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:110:in `calculate'
        from /usr/local/bundle/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:49:in `initialize'
        from /usr/local/bundle/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `new'
        from /usr/local/bundle/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `<module:Libc>'
        from /usr/local/bundle/gems/ethon-0.13.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
        from /usr/local/bundle/gems/ethon-0.13.0/lib/ethon/libc.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/bundle/gems/ethon-0.13.0/lib/ethon.rb:16:in `<top (required)>'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/bundle/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/bundle/gems/html-proofer-3.19.1/lib/html-proofer/url_validator.rb:3:in `<top (required)>'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/bundle/gems/html-proofer-3.19.1/lib/html-proofer.rb:7:in `block in require_all'
        from /usr/local/bundle/gems/html-proofer-3.19.1/lib/html-proofer.rb:6:in `each'
        from /usr/local/bundle/gems/html-proofer-3.19.1/lib/html-proofer.rb:6:in `require_all'
        from /usr/local/bundle/gems/html-proofer-3.19.1/lib/html-proofer.rb:12:in `<top (required)>'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        from /usr/local/bundle/gems/html-proofer-3.19.1/bin/htmlproofer:8:in `<top (required)>'
        from /usr/local/bundle/bin/htmlproofer:23:in `load'
        from /usr/local/bundle/bin/htmlproofer:23:in `<main>'
make: *** [Makefile:16: project-test] Error 1
```

I don't have error whith  `v3.19.0` or less.

**Comment by gjtorikian** [comment]
I’m not sure what the issue here could be, but you will need to open the issue with the maintainer of the Docker image: https://github.com/klakegg/docker-html-proofer

I see that the image was updated two days ago, perhaps a dependency was mistakenly removed.
