### ISSUE TITLE
check_favicon breaks with Error:  undefined method `rel' for #<HTMLProofer::Element:0x00007f7c1b982940>

### ISSUE THREAD

**Issue by arska** [gjtorikian/html-proofer#652]
html-proofer breaks with an error and stacktrace when enabling --check_favicon on https://handbook.vshn.ch/

Test cases:
Works:

```
$ wget -m https://handbook.vshn.ch/

$ docker run -v $PWD:/src klakegg/html-proofer:3.19.2 --only-4xx --http-status-ignore "400,429" --url-ignore "/community.sociocracy30.org/" --allow-hash-href --check-html --empty-alt-ignore --check-opengraph handbook.vshn.ch/
Running ["ScriptCheck", "OpenGraphCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["handbook.vshn.ch/"] on *.html... 


Checking 677 external links...
Ran on 134 files!


HTML-Proofer finished successfully.

```

Breaks:
```
$ wget -m https://handbook.vshn.ch/

$ docker run -v $PWD:/src klakegg/html-proofer:3.19.2 --only-4xx --http-status-ignore "400,429" --url-ignore "/community.sociocracy30.org/" --allow-hash-href --check-html --empty-alt-ignore --check-favicon --check-opengraph handbook.vshn.ch/
Running ["ScriptCheck", "OpenGraphCheck", "LinkCheck", "ImageCheck", "HtmlCheck", "FaviconCheck"] on ["handbook.vshn.ch/"] on *.html... 


htmlproofer 3.19.2 | Error:  undefined method `rel' for #<HTMLProofer::Element:0x00007f7c1b982940>
/usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/check/favicon.rb:10:in `block in run': undefined method `rel' for #<HTMLProofer::Element:0x00007f7c1b982940> (NoMethodError)
	from /usr/local/bundle/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	from /usr/local/bundle/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
	from /usr/local/bundle/gems/nokogiri-1.11.7-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/check/favicon.rb:6:in `run'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:113:in `block (2 levels) in check_parsed'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:110:in `each'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:110:in `block in check_parsed'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:109:in `each'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:109:in `check_parsed'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:137:in `check_path'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:98:in `block in process_files'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:98:in `map'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:98:in `process_files'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:76:in `check_files'
	from /usr/local/bundle/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:48:in `run'
	from /usr/local/bundle/gems/html-proofer-3.19.2/bin/htmlproofer:111:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/local/bundle/gems/html-proofer-3.19.2/bin/htmlproofer:11:in `<top (required)>'
	from /usr/local/bundle/bin/htmlproofer:23:in `load'
	from /usr/local/bundle/bin/htmlproofer:23:in `<main>'

```

**Comment by gjtorikian** [comment]
Hi—[the next version of HTMLProofer](https://github.com/gjtorikian/html-proofer/issues/669) has completely rewritten this check and this is no longer a problem. I am going to close this issue out, as I'm just one person and can't maintain both the 3.x and 4.x features. ✌️
