### ISSUE TITLE
Example cache config not working

### ISSUE THREAD

**Issue by fangyi-zhou** [gjtorikian/html-proofer#723]
I have in my argument

`--cache "{ \"cache\": { \"timeframe\": { \"external\": \"30d\" } } }"`, as suggested by the README file (btw, the one in README is not a valid JSON)

and got the following error

```
htmlproofer 4.0.1 | Error:  undefined method `[]' for nil:NilClass

        @external_timeframe = parsed_timeframe(options[:timeframe][:external])
                                                                  ^^^^^^^^^^^
/usr/share/gems/gems/html-proofer-4.0.1/lib/html_proofer/cache.rb:33:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)

        @external_timeframe = parsed_timeframe(options[:timeframe][:external])
                                                                  ^^^^^^^^^^^
	from /usr/share/gems/gems/html-proofer-4.0.1/lib/html_proofer/runner.rb:19:in `new'
	from /usr/share/gems/gems/html-proofer-4.0.1/lib/html_proofer/runner.rb:19:in `initialize'
	from /usr/share/gems/gems/html-proofer-4.0.1/lib/html_proofer.rb:46:in `new'
	from /usr/share/gems/gems/html-proofer-4.0.1/lib/html_proofer.rb:46:in `check_directories'
	from /usr/share/gems/gems/html-proofer-4.0.1/bin/htmlproofer:86:in `block (2 levels) in <top (required)>'
	from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/share/gems/gems/html-proofer-4.0.1/bin/htmlproofer:11:in `<top (required)>'
	from /usr/bin/htmlproofer:25:in `load'
	from /usr/bin/htmlproofer:25:in `<top (required)>'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
	from /usr/share/gems/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
	from /usr/share/gems/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/share/gems/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
	from /usr/bin/bundle:25:in `load'
	from /usr/bin/bundle:25:in `<main>'
```

**Comment by fangyi-zhou** [comment]
Turns out the correct invocation is `--cache "{ \"timeframe\": { \"external\": \"30d\" } }"`
