### ISSUE TITLE
Redirected links don't report original href in log

### ISSUE THREAD

**Issue by holic** [gjtorikian/html-proofer#77]
I'm seeing some errors appear for links that don't actually exist in the HTML files specified. This is due to a link in the HTML redirecting to another URL and that end URL being reported in the log rather than the original URL linked. Made it a bit tough to find the broken link in a page with a pile of links.

**Comment by holic** [comment]
Reporting seems a bit better lately. Any update on the overall issue?

**Comment by holic** [comment]
I found another case where this is happening. Here's an example of the final report:

```
- ./_site/2009/03/why-you-should-buy-a-tel-domain-name.html
  *  External link http://www.cnet.com/html/404.html failed: 404 No error
```

The end URL is what is getting reported (a custom 404 page) while the original URL is http://asia.cnet.com/blogs/geekonomics/post.htm?id=63009224. However, the verbose log spits out the original URL:

```
ETHON:         performed EASY effective_url=http://www.cnet.com/html/404.html response_code=404 return_code=ok total_time=11.379996
Received a 404 for http://asia.cnet.com/blogs/geekonomics/post.htm?id=63009224 in ./_site/2009/03/why-you-should-buy-a-tel-domain-name.html

...

ETHON:         performed EASY effective_url=http://www.cnet.com/html/404.html response_code=404 return_code=ok total_time=6.384453
Received a 404 for http://www.cnet.com/html/404.html in ./_site/2009/03/why-you-should-buy-a-tel-domain-name.html
```

Something is going on between the first failure and the second failure where the original URL is lost.

**Comment by holic** [comment]
Thanks @gjtorikian. Is 2.0.2 published? Travis-CI is reporting the following issue in 2.0.1:

```
NameError: `@data-src' is not allowed as an instance variable name
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer/checkable.rb:14:in `instance_variable_set'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer/checkable.rb:14:in `block in initialize'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer/checkable.rb:12:in `each_pair'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer/checkable.rb:12:in `initialize'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer/checks/images.rb:28:in `new'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer/checks/images.rb:28:in `block in run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/home/travis/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
/home/travis/.rvm/gems/ruby-2.1.5/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer/checks/images.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer.rb:121:in `block (2 levels) in check_files_for_internal_woes'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer.rb:118:in `each'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer.rb:118:in `block in check_files_for_internal_woes'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:428:in `call'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:428:in `call_with_index'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:334:in `process_incoming_jobs'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:316:in `block in worker'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:309:in `fork'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:309:in `worker'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:297:in `block in create_workers'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:296:in `each'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:296:in `create_workers'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:253:in `work_in_processes'
/home/travis/.rvm/gems/ruby-2.1.5/gems/parallel-1.3.3/lib/parallel.rb:191:in `map'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer.rb:114:in `check_files_for_internal_woes'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer.rb:100:in `check_directory_of_files'
/home/travis/.rvm/gems/ruby-2.1.5/gems/html-proofer-2.0.1/lib/html/proofer.rb:75:in `run'
/home/travis/build/iwantmyname/blog/Rakefile:18:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by gjtorikian** [comment]
2.0.2 is indeed published. It fixes that specific problem. Sorry!

**Comment by holic** [comment]
I'm still seeing 2.0.2 as the latest: https://rubygems.org/gems/html-proofer (not sure how long it takes for this to update, though)

**Comment by gjtorikian** [comment]
2.0.2 *is* the latest. The bug you're seeing was found and fixed: https://github.com/gjtorikian/html-proofer/pull/159
