### ISSUE TITLE
Options validation breaking for booleans

### ISSUE THREAD

**Issue by jemrobinson** [gjtorikian/html-proofer#773]
## Problem

Setting some HTML proofer boolean flags on the command-line fails as follows:

```
htmlproofer html --allow-missing-href=true
htmlproofer 4.4.2 | Error:  Invalid value for 'allow_missing_href': 'true'. Expected FalseClass.
/usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/lib/html_proofer/configuration.rb:103:in `block in validate_options': Invalid value for 'allow_missing_href': 'true'. Expected FalseClass. (TypeError)
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/lib/html_proofer/configuration.rb:99:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/lib/html_proofer/configuration.rb:99:in `validate_options'
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/lib/html_proofer/configuration.rb:52:in `generate_defaults'
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/lib/html_proofer/runner.rb:13:in `initialize'
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/lib/html_proofer.rb:47:in `new'
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/lib/html_proofer.rb:47:in `check_directories'
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/bin/htmlproofer:97:in `block (2 levels) in <top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/local/lib/ruby/gems/3.1.0/gems/html-proofer-4.4.2/bin/htmlproofer:11:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/bin/htmlproofer:25:in `load'
	from /usr/local/lib/ruby/gems/3.1.0/bin/htmlproofer:25:in `<main>'
```

## Cause

The update validation logic added in 12a9409c stops boolean parameters from being changed. This is because Ruby treats `TrueClass` and `FalseClass` separately, so the logic at line 103 of `lib/html_proofer/configuration.rb`:

```
raise TypeError, "Invalid value for '#{key}': '#{value}'. Expected #{default_value.class}." unless value.is_a?(default_value.class)
```

will always raise a `TypeError` if the user provides a `false` for a parameter which defaults to `true` or vice-versa.

**Comment by ribbons** [comment]
I'm also hitting this issue when calling `HTMLProofer.check_directory` directly.

**Comment by gjtorikian** [comment]
Shoot. Will revert and release a patch now.

**Comment by gjtorikian** [comment]
closed by https://github.com/gjtorikian/html-proofer/pull/774

**Comment by jemrobinson** [comment]
Thanks for the extremely quick response @gjtorikian 🎉
